import 'dart:ui';

import 'package:bachaoo/features/catelog/controllers/catelog_controller.dart';
import 'package:bachaoo/features/deals/models/deal_model.dart';
import 'package:bachaoo/features/discounts/models/discount_model.dart';
import 'package:get/get.dart';

class CatalogDealsBinding extends Bindings {
  @override
  void dependencies() {
    Get.put<CatalogController<DealModel>>(
      CatalogController<DealModel>(
        allItems: fetchMockDeals(),
        ratingOf: (d) => d.rating ?? 0,
        categoryOf: (d) => d.category ?? '',
        titleOf: (d) => d.title,
        createdAtOf: (d) =>
            d.createdAt ?? DateTime.fromMillisecondsSinceEpoch(0),
        popularityOf: (d) => d.popularityScore ?? 0,
      ),
      tag: 'all_deals',
    );
  }
}

class CatalogDiscountsBinding extends Bindings {
  @override
  void dependencies() {
    Get.put<CatalogController<DiscountModel>>(
      CatalogController<DiscountModel>(
        allItems: fetchMockDiscounts(),
        ratingOf: (d) => d.rating ?? 0,
        categoryOf: (d) => d.category ?? '',
        titleOf: (d) => d.title,
        createdAtOf: (d) =>
            d.createdAt ?? DateTime.fromMillisecondsSinceEpoch(0),
        popularityOf: (d) => d.popularityScore ?? 0,
      ),
      tag: 'all_discounts',
    );
  }
}

List<DealModel> fetchMockDeals() {
  return [
    DealModel(
      id: 'd1',
      imageUrl: 'https://picsum.photos/seed/kfc-deal/400/400',
      badgeLabel: '1+1 FREE',
      brandTag: 'KFC',
      brandColor: const Color(0xFFC8102E),
      logoUrl: 'https://www.google.com/s2/favicons?sz=128&domain=kfc.com',
      title: 'Zinger Burger Deal 1x1',
      subtitle: 'KFC Satellite Town',
      currentPrice: '899',
      originalPrice: '1,798',
      category: 'Food',
      rating: 4.6,
      createdAt: DateTime(2026, 9, 12),
      popularityScore: 980,
    ),
    DealModel(
      id: 'd2',
      imageUrl: 'https://picsum.photos/seed/nawaab-deal/400/400',
      badgeLabel: 'Family Deal',
      brandTag: 'NRR',
      brandColor: const Color(0xFF8A6A2F),
      title: 'BBQ Platter for 4',
      subtitle: 'Nawaab Royal Restaurant',
      currentPrice: '2,499',
      originalPrice: '3,200',
      category: 'Food',
      rating: 4.2,
      createdAt: DateTime(2026, 9, 9),
      popularityScore: 640,
    ),
    DealModel(
      id: 'd3',
      imageUrl: 'https://picsum.photos/seed/metro-deal/400/400',
      badgeLabel: 'Weekly Deal',
      brandTag: 'MET',
      brandColor: const Color(0xFF0057A3),
      title: 'Grocery Bundle — Rice, Oil & Pulses',
      subtitle: 'Metro Cash & Carry',
      currentPrice: '3,150',
      originalPrice: '3,900',
      category: 'Super Market',
      rating: 4.0,
      createdAt: DateTime(2026, 9, 5),
      popularityScore: 410,
    ),
    DealModel(
      id: 'd4',
      imageUrl: 'https://picsum.photos/seed/glow-deal/400/400',
      badgeLabel: 'Spa Combo',
      brandTag: 'GLW',
      brandColor: const Color(0xFFD46A9F),
      title: 'Facial + Hair Spa Combo',
      subtitle: 'Glow Beauty Salon',
      currentPrice: '3,000',
      originalPrice: '5,500',
      category: 'Beauty & Care',
      rating: 4.8,
      createdAt: DateTime(2026, 9, 14),
      popularityScore: 1120,
    ),
    DealModel(
      id: 'd5',
      imageUrl: 'https://picsum.photos/seed/brainy-deal/400/400',
      badgeLabel: 'Enroll Now',
      brandTag: 'BRN',
      brandColor: const Color(0xFF2E7D32),
      title: 'IELTS Prep Course — 6 Weeks',
      subtitle: 'Brainwave Academy',
      currentPrice: '8,000',
      originalPrice: '12,000',
      category: 'Education',
      rating: 4.3,
      createdAt: DateTime(2026, 8, 30),
      popularityScore: 260,
    ),
    DealModel(
      id: 'd6',
      imageUrl: 'https://picsum.photos/seed/cinema-deal/400/400',
      badgeLabel: 'Couple Pass',
      brandTag: 'CNP',
      brandColor: const Color(0xFF6A1B9A),
      title: '2 Movie Tickets + Popcorn Combo',
      subtitle: 'Cinepax Sargodha',
      currentPrice: '1,200',
      originalPrice: '1,800',
      category: 'Entertainment',
      rating: 4.5,
      createdAt: DateTime(2026, 9, 15),
      popularityScore: 875,
    ),
    DealModel(
      id: 'd7',
      imageUrl: 'https://picsum.photos/seed/carwash-deal/400/400',
      badgeLabel: 'Full Package',
      brandTag: 'SFM',
      brandColor: const Color(0xFF37474F),
      title: 'Full Car Wash + Wax Package',
      subtitle: 'Suzuki Falcon Motors',
      currentPrice: '1,500',
      originalPrice: '2,200',
      category: 'Auto Mobiles',
      rating: 3.9,
      createdAt: DateTime(2026, 8, 19),
      popularityScore: 180,
    ),
    DealModel(
      id: 'd8',
      imageUrl: 'https://picsum.photos/seed/dentist-deal/400/400',
      badgeLabel: 'First Visit',
      brandTag: 'SDC',
      brandColor: const Color(0xFF00897B),
      title: 'Dental Checkup + Scaling',
      subtitle: 'Smile Dental Clinic',
      currentPrice: '1,800',
      originalPrice: '3,000',
      category: 'Health',
      rating: 4.7,
      createdAt: DateTime(2026, 9, 10),
      popularityScore: 590,
    ),
    DealModel(
      id: 'd9',
      imageUrl: 'https://picsum.photos/seed/threads-deal/400/400',
      badgeLabel: 'Season Sale',
      brandTag: 'TRD',
      brandColor: const Color(0xFF4E342E),
      title: 'Unstitched 3-Piece Lawn Suit',
      subtitle: 'Threads & Co.',
      currentPrice: '2,100',
      originalPrice: '3,500',
      category: 'Fashion',
      rating: 4.1,
      createdAt: DateTime(2026, 9, 1),
      popularityScore: 330,
    ),
    DealModel(
      id: 'd10',
      imageUrl: 'https://picsum.photos/seed/laundry-deal/400/400',
      badgeLabel: 'Bulk Discount',
      brandTag: 'QCL',
      brandColor: const Color(0xFF1565C0),
      title: 'Dry Clean 10 Items Bundle',
      subtitle: 'QuickClean Laundry Services',
      currentPrice: '1,000',
      originalPrice: '1,500',
      category: 'Services',
      rating: 3.7,
      createdAt: DateTime(2026, 8, 22),
      popularityScore: 95,
    ),
  ];
}

List<DiscountModel> fetchMockDiscounts() {
  return [
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/dhuaan-disc/400/400',
      discountLabel: '15% off',
      title: 'Dhuaan N Dhukan',
      subtitle: 'Zafarullah Chowk, Old Satellite Town',
      description: 'Get 15% off your entire bill on dine-in orders.',
      tags: const ['Dine-in', 'Cash & card', 'Cap Rs 1,500'],
      category: 'Food',
      rating: 5.0,
      createdAt: DateTime(2026, 9, 13),
      popularityScore: 1400,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/chobara-disc/400/400',
      discountLabel: '12% off',
      title: 'Chobara Restaurant',
      subtitle: 'Queen Road, Sargodha',
      description: 'Enjoy 12% off on all food items, dine-in only.',
      tags: const ['Dine-in', 'Cash only'],
      category: 'Food',
      rating: 4.4,
      createdAt: DateTime(2026, 9, 4),
      popularityScore: 720,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/almart-disc/400/400',
      discountLabel: '8% off',
      title: 'Al-Barkat Super Store',
      subtitle: 'Club Road, Sargodha',
      description: 'Flat 8% off on groceries above Rs 2,000.',
      tags: const ['In-store', 'Cash & card'],
      category: 'Super Market',
      rating: 3.8,
      createdAt: DateTime(2026, 8, 28),
      popularityScore: 150,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/glamour-disc/400/400',
      discountLabel: '20% off',
      title: 'Glamour Beauty Lounge',
      subtitle: 'DHA Phase 2, Sargodha',
      description: '20% off on all salon services this month.',
      tags: const ['Appointment required'],
      category: 'Beauty & Care',
      rating: 4.9,
      createdAt: DateTime(2026, 9, 16),
      popularityScore: 1650,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/skillup-disc/400/400',
      discountLabel: '25% off',
      title: 'SkillUp Learning Center',
      subtitle: 'University Road, Sargodha',
      description: '25% off on all short courses enrolled this quarter.',
      tags: const ['New students only'],
      category: 'Education',
      rating: 4.0,
      createdAt: DateTime(2026, 8, 25),
      popularityScore: 210,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/funzone-disc/400/400',
      discountLabel: '10% off',
      title: 'FunZone Arcade & Bowling',
      subtitle: 'Railway Road, Sargodha',
      description: '10% off on game tokens and bowling lanes.',
      tags: const ['Weekdays only'],
      category: 'Entertainment',
      rating: 4.3,
      createdAt: DateTime(2026, 9, 8),
      popularityScore: 480,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/falcon-disc/400/400',
      discountLabel: '20% labour',
      title: 'Suzuki Falcon Motors',
      subtitle: 'Motorway Road, Sargodha',
      description: '20% off labour charges on all servicing.',
      tags: const ['Service only', 'No parts'],
      category: 'Auto Mobiles',
      rating: 3.9,
      createdAt: DateTime(2026, 8, 19),
      popularityScore: 190,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/careplus-disc/400/400',
      discountLabel: '15% off',
      title: 'CarePlus Pharmacy & Clinic',
      subtitle: 'Farooq-e-Azam Road, Sargodha',
      description: '15% off on consultation fee and OTC medicines.',
      tags: const ['Walk-in', 'Cash & card'],
      category: 'Health',
      rating: 4.6,
      createdAt: DateTime(2026, 9, 11),
      popularityScore: 610,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/stitchhub-disc/400/400',
      discountLabel: '30% off',
      title: 'StitchHub Fashion House',
      subtitle: 'Bhalwal Road, Sargodha',
      description: '30% off on ready-to-wear collection, this week only.',
      tags: const ['In-store only', 'Limited stock'],
      category: 'Fashion',
      rating: 4.2,
      createdAt: DateTime(2026, 9, 2),
      popularityScore: 340,
    ),
    DiscountModel(
      imageUrl: 'https://picsum.photos/seed/swiftfix-disc/400/400',
      discountLabel: '10% off',
      title: 'SwiftFix Home Services',
      subtitle: 'Available across Sargodha',
      description: '10% off on electrical and plumbing call-outs.',
      tags: const ['Book via app', 'Cash on completion'],
      category: 'Services',
      rating: 3.6,
      createdAt: DateTime(2026, 8, 21),
      popularityScore: 88,
    ),
  ];
}
